*Variable labels

{
la var c_wt_6m		"Child Weight (at 6 months)"
la var c_wt_1y		"Child Weight (at 1 year)"
la var c_ht_6m		"Child Height (at 6 months)"
la var c_ht_1y		"Child Height (at 1 year)"
la var hamd_6m		"Mother's Hamilton score (at 6 months)"
la var hamd_1y		"Mother's Hamilton score (at 1 year)"
la var fsiq		"Child Full Scale IQ (age 7)"
la var c_wt		"Child Weight (age 7)"
la var c_ht		"Child Height (age 7)"
la var spence		"Child Spence anxiety (age 7)"
la var sdq_sum		"Child SDQ (age 7)"
la var home		"Home score (age 7)"
la var treat 		"Treatment"
la var girlXtreat 	"Girl $\times$ Treat"
la var depXtreat 	"Depr $\times$ Treat"
la var dep_sample 	"Depr"
la var grandmaXtreat 	"Grandma $\times$ Treat"
la var tot_edu	  	"Low educ"	 
la var toteduXtreat	"Low educ $\times$ Treat"

la var var161 		"Electricity"
la var var162		"Radio"
la var var163		"TV"
la var var164		"Refrigerator"
la var var165		"Bicycle"
la var var167 		"Air con"
la var var168		"Washing machine"
la var var169		"Water pump"
la var var170		"Car"
la var var172		"Piped drinking water"
la var var183		"Flush toilet"
la var var188		"Brick/concrete walls"
la var var195		"No. member per room"
la var var198		"Has debt"
la var var613 		"Husband supports in difficult situations (12mo)"

la var treat 		"Treated"
la var dep_sample 	"Baseline depressed"
la var age_baseline 	"Mother's age"
la var age_baseline_sq 	"Mother's age$^2$"
la var famstruct_baseline	"Nuclear family (baseline)"
la var var29 		"Joint/extended family structure"
la var c_sex 		"Child gender"
la var edu_mo_baseline 	"Mother's education (yrs)"
la var edu_fa_baseline 	"Father's education (yrs)"
la var no_kids_baseline "Parity"
la var kids_no 		"Parity"
la var ln_inc_baseline 	"log(Income)"
la var grandmother_baseline 	"Grandmother lives with"
la var hamd_baseline 	"Depression score (Hamilton)"
la var bdq_baseline 	"Disability score (BDQ)"
la var mspss_baseline 	"Perceived Social Support score (MSPSS)"
la var employed_fa_baseline 	"Father employed"
la var occupation_fa_baseline 	"Father's occupation non-manual worker"
la var ses_baseline 	"SES (1=Rich, 5=Poor)"
la var mo_ht 		"Mother's height (m)"
la var mo_bmi 		"Mother's BMI"
la var ltfu_moved 	"LTFU because moved"
la var first_child 	"Index child is first born"

la var depressed_6m 	"Mother depressed"
la var hamd_6m 		"Depression score (Hamilton)"
la var bdq_6m 		"Disability score (BDQ)"
la var mspss_6m 	"Perceived Social Support score (MSPSS)"
la var ses_6m 		"SES (6m)"
la var depressed_1y 	"Mother depressed"
la var hamd_1y 		"Hamilton score"
la var bdq_1y 		"BDQ score"
la var mspss_1y 	"Perceived Social Support score (MSPSS)"
la var ses_1y 		"SES (1y)"
la var grandmother_1y 	"Grandmother lives with"
la var c_wt_1y 		"Child weight (km)"
la var c_ht_1y		"Child height (cm)"

la var grandmother 	"Grandmother lives with"
la var genhealth 	"Mother's general health (1=vgood 5=vbad)"
la var famstruct 	"Joint/extended family structure"
la var ses 		"SES (7y) (0=poorest, 4=richest)"
la var ses_lhw_rating 	"SES (1=Rich, 5=Poor)"
la var age 		"Mother's age"
la var edu_mo 		"Mother's education"
la var adults_inhouse 	"Number of adults living with"
la var no_kids 		"Number of kids"
la var no_kids_recent 	"Number of kids born to mother in last 7 years"
la var avg_age_kids_recent 	"Avg age if kids born to mother in last 7 yrs"
la var edu_fa 		"Father's education"
la var employed_fa 	"Father employed"
la var occupation_fa 	"Father's occupation non-manual worker"
la var ln_income 	"log(Income)"
la var mo_76 		"Has debt"  
la var mo_55 		"Piped drinking water"
la var mo_61 		"Flush toilet"

la var notdep		"Not depressed at 7y"
la var impaired 	"Symptoms don't distress/impair" 
la var notdep1213	"Not depressed in past 2yrs"
la var notdep2011 	"Not depressed 2011"
la var notdep2012 	"Not depressed 2012"
la var notdep2013 	"Not depressed 2013"  
la var dur_notdep 	"Yrs not dep. since 2011"
la var scid_tot   	"\# Dep. symptoms absent"
la var basicneeds 	"Have enough for basic needs"
la var enoughfood 	"Have enough for food"
la var nodebt		"No debt"
la var ses		"SES (0=poorest, 4=richest)"
la var pipedwater_7y	"Have piped water"
la var flushtoilet_7y	"Have flush toilet"
la var gasstove_7y	"Have gas stove"
la var transport_7y	"Transport mode (0=none, 5=car)"




la var maritalscale		"Marital quality scale (7y)"
la var relationship_husb	"Relationship husband (7y)"
la var nonviolent		"Husband nonviolent (7y)"
la var relationship_inlaw	"Relationship m-in-law (7y)"
la var maritalscale_1y		"Marital quality scale (1y)"
la var relationship_husb_1y	"Relationship husband (1y)"
la var nonviolent_1y		"Husband nonviolent (1y)"
la var relationship_inlaw_1y	"Relationship m-in-law (1y)"
la var relation_traj 		"Relationship quality"

la var mspss_tot	"Perceived social support"
la var pipedwater_7y	"Piped water (7y)"	
la var flushtoilet_7y	"Flush toilet (7y)"
la var gasstove_7y	"Gas stove (7y)"
la var transport_7y	"Mode of transport (7y)"
la var notunwell	"Mother never been unwell (7y)"
la var days_healthy	"Healthy days in past 30 (7y)"
la var genhealth	"Overall health (0-4) (7y)"
la var paid_notforgone	"Days not forgone work due to illness (in past 180) (7y)"

la var employed_mo	"Mother employed (7y)"
la var employed_fa	"Husband employed (7y)"

la var empowered	"Mother controls spending (7y)"
la var mo_185		"Mother gets pocket money (7y)"
la var var611 		"Mother gets pocket money (1y)"


la var ln_income_mo	"Mother's income (ln) (7y)"
la var ln_income_fa	"Monthly income (ln) (7y)"
la var ln_income_fa_6m	"Monthly income (ln) (6m)"
la var ln_income_fa_1y	"Monthly income (ln) (1y)"

la var ln_income_hh	"HH's income w/o mother's (ln) (7y)"

la var income_mo	"Mother's income (100s PKR) (7y)"
la var income_fa	"Husband's income (100s PKR) (7y)"
la var income_fa_1y	"Husband's income (100s PKR) (1y)"
la var income_fa_6m	"Husband's income (100s PKR) (6m)"
la var income_hh	"HH's income w/o mother's (100s PKR) (7y)"

la var expend_food	"Monthly expend. on food (100s PKR) (7y)"
la var expend_med	"Monthly expend. on medical (100s PKR) (7y)"
la var expend_educ	"Expend. on educ (100s PKR) (7y)"
la var expend_tot	"Total Monthly Expend (100s PKR) (7y)"

la var ln_expend_food	"Monthly expend. on food (ln) (7y)"
la var ln_expend_med	"Monthly expend. on medical (ln) (7y)"
la var ln_expend_educ	"Monthly expend. on educ (ln) (7y)"
la var ln_expend_tot	"Total Monthly Expend (ln) (7y)"

la var age 		"Age"
la var edu_mo 		"Mother's education"
la var edu_fa 		"Father's education"
la var grandmother 	"Grandmother lives with"
la var girl 		"Index child is girl"
la var c_age_int 	"Age of index child"
la var kids_total	"Parity"
la var adults_inhouse 	"Adults in house"

la var dur_tot 		"Total duration of depressive episodes (yrs)"
la var dur_tot_exact 	"Duration of recalled depressive episodes (yrs)"
la var dep_tot 		"Number of recalled depressive episodes"
la var dep_tot2 	"Number of depressive episodes since 2007"
la var mspss_tot 	"Perceived social support score (MSPSS)"
la var depressed 	"Depressed (7y)"
la var recover_perm 	"Recovered permanently"
la var recover_never 	"Never recovered"
la var dep_ever 	"Depressed ever between 2008-2013"
la var dep_ever_recall 	"Depressed between 2008-2013 (recall only)"
la var dep2008 		"Depressed in 2008"
la var dep2009 		"Depressed in 2009"
la var dep2010 		"Depressed in 2010"
la var dep2011 		"Depressed in 2011"
la var dep2012 		"Depressed in 2012"
la var dep2013 		"Depressed in 2013"

la var vci 		"VCI"
la var vsi 		"VSI"
la var fri 		"FRI"
la var wmi 		"WMI"
la var psi 		"PSI"
la var fsiq  		"FSIQ"
la var zwaz  		"Weight"
la var zhaz  		"Height"
la var stunted 		"Stunted (Height<-2SD)"
la var thin 		"Thin (BMI<-2SD)"
la var spence 		"Spence"
la var sdq_sum 		"SDQ"
la var mo_491 		"Hospitalized"
la var mo_490 		"Severe illness"
la var mo_485 		"Eyesight probs"
la var mo_488 		"Hearing probs"
la var peg_time		"Pegboard time"
la var urdu 		"Urdu"
la var math 		"Math"
la var stroop 		"Stroop"
la var ch_9 		"Grade"
la var attendance 	"Attendance"
la var private_sch 	"Private school"
la var class_size 	"Class size"
la var mo_75 		"Educ Expenditure"
la var expect_sch 	"Expected grade attainment"
la var home_res 	"Responsivity"
la var home_mat 	"Maturity"
la var home_emo 	"Emotional climate"
la var home_learn 	"Learning materials"
la var home_enrich 	"Enrichment"
la var home_f_comp 	"Companionship"
la var home_f_inter 	"Integration"
la var home_env 	"Physical environ."
la var home 	"Total"

la var PPI	 	"Parenting practices inventory	"
la var PPI_neg	 	"Parenting practices (negative)	"
la var PPI_pos	 	"Parenting practices (positive)	"
la var home_res		"HOME: responsivity	"
la var home_mat		"HOME: maturity	"
la var home_emo		"HOME: emotional climate	"
la var mo_358	 	"Frequency of mother play	"
la var mo_359	 	"Frequency of father play	"
la var home_learn	"HOME: learning materials	"
la var home_enrich	"HOME: enrichment	"
la var home_f_comp	"HOME: companionship	"
la var home_f_inter	"HOME: integration	"
la var home_env		"HOME: physical environment	"
la var mo_75	 	"Education expend.(100s PKR)	"
la var expect_sch	"Expected grade attainment	"
la var mo_360	 	"Someone helps with studies	"
la var private_sch	"Private school	"
la var class_size_2	"Class size	"
la var class_size	"Class size	"

la var ch_16	 	"No. teachers in school	"
la var ch_25	 	"No. rooms in school	"
la var ch_26	 	"No. rooms in use	"
la var classroom	"Classroom amenities	"
la var schoolqual	"School amenities	"
la var fsiq	 	"Full scale IQ	"
la var urdu	 	"Urdu score	"
la var math	 	"Math score	"
la var stroop	 	"Executive function (Stroop)	"
la var ch_9	 	"Grade	"
la var zwaz	 	"Weight-for-age (z)	"
la var zhaz	 	"Height-for-age (z)	"
la var motor	 	"Motor function	"
la var 	motor2 		"Motor function"
la var mo_491_2	 	"No hospitalization	"
la var mo_490_2	 	"No severe illness	"
la var mo_485_2	 	"No eyesight problems	"
la var mo_488_2	 	"No hearing problems	"
la var mo_491	 	"Hospitalization	"
la var mo_490	 	"Severe illness	"
la var mo_485	 	"Eyesight problems	"
la var mo_488	 	"Hearing problems	"
la var home	 	"HOME	"
la var sdq_sum_2	"SDQ: no behavioral problems	"
la var spence_2	 	"Spence: no anxiety problems	"
la var hamd_baseline	"Baseline Hamilton depression score	"
la var bdq_baseline	"Baseline BDQ score	"
la var mspss2	 	"Baseline MSPSS score	"
la var sdq_sum	 	"Behavioral issues (SDQ)"
la var spence	 	"Anxiety (Spence)"
 
 
la var schoolqual	"School Quality"
la var ch_27	 	"School has office"
la var ch_28	 	"School has playground"
la var ch_29	 	"School has library"
la var ch_30	 	"Library books visably in use"
la var ch_31	 	"School has water source"
la var ch_32	 	"School has clean drinking water"
la var ch_33	 	"School has fencing"
la var ch_34	 	"School has computers"
la var ch_35	 	"Computers visably in use"
						
la var home	 	"HOME inventory"
la var home_res	 	"HOME: Responsivity"
la var home_mat	 	"HOME: Encouragement of maturity"
la var home_emo	 	"HOME: Emotional climate"
la var home_learn	"HOME: Learning materials"
la var home_enrich	"HOME: Enrichment"
la var home_f_comp	"HOME: Family companionship	"
la var home_f_inter	"HOME: Family integration	"
la var home_env	 	"HOME: Physical environment	"
									
la var spence	 	"Spence Child Anxiety Scale	"
la var panic	 	"SCAS: Panic and agoraphobia	"
la var separation	"SCAS: Separation	"
la var injury_fear	"SCAS: Injury fear	"
la var social_phobia	"SCAS: Social phobia	"
la var obc	 	"SCAS: Obsessive-compulsive	"
la var gad	 	"SCAS: General anxiety	"
						
la var sdq_sum	 	"SDQ Total Score	"
la var sdq_emo	 	"SDQ: Emotional	"
la var sdq_cond		"SDQ: Conduct problems	"
la var sdq_hyper	"SDQ: Hyperactivity	"
la var sdq_peer		"SDQ: Peer problems	"
la var sdq_pro	 	"SDQ: Prosocial	"

						
la var fsiq		"WPPSI Full Scale IQ	"
la var vci	 	"WPPSI: Verbal comprehension	"
la var vsi	 	"WPPSI: Visual spatial	"
la var fri	 	"WPPSI: Fluid reasoning	"
la var wmi	 	"WPPSI: Working memory	"
la var psi	 	"WPPSI: Processing speed	"


la var PPI	 	"Parenting practices inventory	"
la var 	PPI_harsh 	"PPI: Not harsh" 
la var 	PPI_harsh4age 	"PPI: Not harsh for age" 
la var 	PPI_inconsistent	"PPI: Consistent" 
la var 	PPI_appropriate	"PPI: Appropriate" 
 
 
la var wealth_baseline 	"Wealth Index"
la var occupation_fa_baseline 	"Father not manual worker"
la var mspss_baseline 	"Perceived social support score"
la var hamd_baseline 	"Hamilton depression score"

la var depindex_0 	"Baseline depression severity"

 
la var cognindex 	"Cognitive development"
la var healthindex 	"Physical development"
la var emoindex 	"Socio-emotional development"

la var notdep2011 	"Not depressed 2011"
la var notdep2012 	"Not depressed 2012"
la var notdep2013 	"Not depressed 2013"  
la var incomeindex 	"Household Wealth Index"
la var expend_tot  	"Total expenditures"
la var motherhealthindex 	"Mother's physical health"
la var motherfinancial 	"Mother's financial empowerment"
la var fatherfinancial 	"Husband's income trajectory"
la var relationshipindex 	"Relationship quality index (7y)"
la var relationshipindex_1y 	"Relationship quality index (1y)"
la var fertility_vars 	"Fertility trajectory index"
la var childmort 	"Sibling survival index"
la var grandmothers 	"Grandmother trajectory"
la var mother_mh 	"Mental health index"
la var socialsupport 	"Social support trajectory"

la var grandmother 	"Grandmother present (7y)"
la var grandmother_1y 	"Grandmother present (1y)"
la var grandmother_6m 	"Grandmother present (6m)"

	
la var depindex_6m 	"Depression index (6mo)"
la var depindex_1y 	"Depression index (12mo)"
la var depindex_7y 	"Depression index (7y)"
la var infantdev_6m 	"Infant health index (6m)"
la var infantdev_1y 	"Infant health index (1y)"
la var parentinputs_infancy 	"Parenting inputs by 1y"
	

la var exclusivebf_6m 	"Exclusive breastfeeding (6mo)"
la var anybf_6m 	"Breastfeeding (6mo)"
la var play_mo_1y 	"Mother play frequency with infant (12mo)"
la var play_fa_1y 	"Father play frequency with infant (12mo)"
la var discussed 	"Discussed child's development with family (12mo)"
la var var618 		"Selected appropriate place for delivery"
la var var619 		"Arranged transport for delivery"
la var var620 		"Arranged finances for delivery"
la var var621 		"Practicing birth spacing (12mo)"
	     
la var c_wt_6m 		"Child weight KG (6mo)"
la var c_wt_1y 		"Child weight KG (12mo)"
la var c_ht_6m 		"Child length CM (6mo)"
la var c_ht_1y 		"Child length CM (12mo)"
la var diarhea_6m 	"Diarrhea episodes (6mo)"
la var diarhea_1y  	"Diarrhea episodes (12mo)"
la var  ari_6m 		"Acute Respiratory Infection (6mo)"
la var ari_1y 		"Acute Respiratory Infection (12mo)"

la var diarhea_6m_flip 	"No Diarrhea episodes (6mo)"
la var diarhea_1y_flip	"No Diarrhea episodes (12mo)"
la var  ari_6m_flip 	"No Acute Respiratory Infection (6mo)"
la var ari_1y_flip 	"No Acute Respiratory Infection (12mo)"

la var HAZ_6 		"Height-for-age (z) 6m"
la var WAZ_6 		"Weight-for-age (z) 6m"
la var WHZ_6 		"Weight-for-height (z) 6m"
la var HAZ_12 		"Height-for-age (z) 1y"
la var WAZ_12 		"Weight-for-age (z) 1y"
la var WHZ_12 		"Weight-for-height (z) 1y"
la var infantdev 	"Infant development index"
la var var599 		"Completed immunization"

la var depressed_6m 	"Depressed (6m)"
la var depressed_1y 	"Depressed (1y)"
la var hamd_6m 		"Depression severity (6m)"
la var hamd_1y 		"Depression severity (1y)"
la var bdq_6m 		"BDQ disability score (6m)"
la var bdq_1y 		"BDQ disability score (1y)"
la var gaf_6m 		"GAF general functioning (6m)"
la var gaf_1y 		"GAF general functioning (1y)"
la var mspss_6m   	"Perceived social support (6m)"
la var mspss_1y 	"Perceived social support (1y)"
la var notdepressed 	"Not depressed at 7y followup"
la var dur_tot_exact 	"Total duration of recalled dep. episodes"
la var notdep_ever_recall 	"Never depressed in recall period"
la var mspss_tot 	"Perceived social support"

la var ses_bl_flipped 	"SES (0=poor, 4=rich)"
la var kids_u7 		"Number kids under 7"
la var mo_emp 		"Empowered"
la var wealth_baseline_4sum 	"Wealth index\tnote{a}"
la var month 		"Index child age (months)"
la var gaf_baseline 	"General functioning (GAF)"
la var attrit 		"LTFU from 1y (N=704)\tnote{b}"
la var attrit2 		"LTFU from baseline (N=903)"

la var var416 		"Weight (kg) (1y)"
la var motherfinancial_7y 	"Mother's financial empowerment (7y)"

la var motherfinancial 	"Mother's financial empowerment"
la var parentmoney 	"Parental investment (monetary)" 
la var parenttime 	"Parental investment (time-intensive)"
la var parentstyle 	"Parenting style"
la var fertility_vars 	"Fertility trajectory"
la var depression_traj 	"Depression trajectory"

la var abortion 	"LTFU: abortion"
la var stillbirth 	"LTFU: stillbirth"
la var childdeath 	"LTFU: child death/illness"
la var motherdeath 	"LTFU: mother death/illness"
la var refused 		"LTFU: refused"
la var moved 		"LTFU: moved"
la var MIL 		"Mother-in-law lives with"
la var maternalgma 	"Mother's mother lives with"
la var femshare 	"\% children female"
}
